version: '3'
services:
    # app:
    #     build: .
    #     ports:
    #       - "8080:8080"
    #  flyway migrate -enterprise -DcherryPick="1,People_view" 
    db:
        image: postgres
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - 5432:5432/tcp
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
volumes:
    db-data:
        driver: local
